config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  namespace :console do
    root to: 'home#index'
    delete "logout", to: "sessions#destroy"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/console/base_controller.rb
module Console
  class BaseController < ApplicationController
    before_action :auth_user

    private

    def auth_user
      if params[:access_token]
        session[:user_id] = params[:access_token]
      end
      @cognito_user = Cognito.get_user_info(session[:user_id])

      raise "You have to sign in!" if @cognito_user.blank?

    end
  end
end

app/controllers/console/home_controller.rb
module Console
  class HomeController < BaseController
    def index
      @email = @cognito_user.user_attributes.find{|a| a.name == "email"}.value
    end
  end
end

app/controllers/console/sessions_controller.rb
module Console
  class SessionsController < BaseController
    def destroy
      # Cognito.sign_out(session[:user_id])
      session.delete(:user_id)
      @cognito_user = nil
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/console/home_helper.rb
module Console::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/console/home/index.html.erb
<h3>Login Success</h3>
<h5>Console Home Screen</h5>
<span>Email login: <%= @email %></span>

<%= link_to "Logout", console_logout_path, method: :delete, data: { confirm: "Do you want to logout?" } %>

app/views/home/index.html.erb
<h3>Home Screen</h3>
<%= link_to "Login", "http://localhost:3000/member/sign_in?#{{redirect_uri: 'http://localhost:3001/console'}.to_query}" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CognitoAuthenApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>